### ISSUE TITLE
Address corner case in block replay

### ISSUE THREAD

**Issue by gballet** [gballet/go-ethereum#212]
There is a potential bug occurring if the limit for the number of keys translated per block is reached right after processing an account's storage, but when the account has not been processed yet. The transition will be marked as completed, but just this account is missing.

See this comment for more context: https://github.com/gballet/go-ethereum/pull/203/files#diff-7ee5f952a6b64b5c8a5db54348910f6e901dcafce4afa172720c40713fe2e78bR233

**Comment by jsign** [comment]
@gballet, I think we already solved this?

**Comment by gballet** [comment]
We did. Closing.
